### ISSUE TITLE
Système d'inscription à une formation

### ISSUE THREAD

**Issue by robin850** [SamuelBzn/ProjetM1#4]
Avant, il faut mettre en place le système de sessions pour les formations. Ça sera un truc assez simple avec juste une date de début et une date de fin.

Ensuite, il faut mettre en place le système d'inscription à une formation.

* Lors du clique sur le bouton d'inscription, rediriger l'utilisateur vers une page lui proposant soit de se connecter, soit de s'inscrire.

   On peut sûrement utiliser ou la page de connexion, ou la page d'inscription, il y a un lien vers l'autre sur chaque.
* Une fois l'utilisateur connecté, le rediriger vers la page listant les sessions
* Une fois la session choisie, le rediriger vers la page de paiement de la formation
  - Mettre en place le système de paiement par PayPal
  - Envoyer un mail de confirmation de paiement

**Comment by SamuelBzn** [comment]
Ajout d'un champ "start_session" et "stop_session" dans le schema.rb
Ajout d'un controller "dashboard" pour afficher les formations d'un utilisateur connecté (en cours de dév)

**Comment by robin850** [comment]
Finish avec https://github.com/SamuelBzn/ProjetM1/commit/dc225a9bc92476c32c01903ce1ed7745ee2ccac9
