### ISSUE TITLE
Petits trucs qui manquent

### ISSUE THREAD

**Issue by robin850** [SamuelBzn/ProjetM1#6]
Quelques petits trucs qui manquent pour le site :

* [x] Un WYSIWYG pour la description des formations
* [x] Un moyen de renseigner le prix de la formation à la création de la formation ou de la session
* [x] Système de recherche ?
* [x] Inscription en tant qu'organisme ou simple utilisateur
* [x] Changement du panneau de gestion du compte en fonction du type d'utilisateur
* [x] Affichage d'une page d'accueil avec la ou les formation(s) de l'utilisateur une fois inscrit

**Comment by SamuelBzn** [comment]
Le WYSIWYG est installé, il suffit de mettre une classe "wysiwyg" sur la textarea.
Gem : froala

**Comment by robin850** [comment]
Ah nice ! :-) T'es chaud (même s'il fait pas froid là ... froala, t'y as compris ? Huh ?).

**Comment by SamuelBzn** [comment]
Tant que les loutes ça reste pour les voitules, ça me va huh

**Comment by SamuelBzn** [comment]
La recherche est implémentée et fonctionnelle pour les formations (commit soon)

**Comment by robin850** [comment]
* https://github.com/SamuelBzn/ProjetM1/commit/6ac23865e2816243fe028c80a401533841bd755c - Internationalisation et petites corrections au niveau du design
* https://github.com/SamuelBzn/ProjetM1/commit/d726399c0f8fb7159c03189d2991dcd4b8750dd7 - inscription pour les organismes via le panel admin
* https://github.com/SamuelBzn/ProjetM1/commit/485c0dd8015a2aeb83b3283dc645aaed1c13a349 - page d'accueil avec les formations de l'utilisateur
* https://github.com/SamuelBzn/ProjetM1/commit/db39894e178693f4630d62ff0713f829d8400778 - dashboard différent pour organisme et étudiant
